size_ratio_base: 1.7
click_through_enabled: false
screen_connect_enabled: true
drag_follow_enabled: true
throw_follow_enabled: true
mouse_follow_enabled: false
bigger_enabled: true
bigger_wait_time: 2700000
bigger_max_size_ratio: 7.0
